"""feat: input table and output table

Revision ID: 22b4952ec9a0
Revises: 
Create Date: 2022-09-19 23:05:11.573779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22b4952ec9a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inputtables',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sepal_length', sa.Float(), nullable=False),
    sa.Column('sepal_width', sa.Float(), nullable=False),
    sa.Column('petal_length', sa.Float(), nullable=False),
    sa.Column('petal_width', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inputtables_id'), 'inputtables', ['id'], unique=False)
    op.create_table('outputtables',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('executed_at', sa.Float(), nullable=False),
    sa.Column('pred_class', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outputtables_id'), 'outputtables', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outputtables_id'), table_name='outputtables')
    op.drop_table('outputtables')
    op.drop_index(op.f('ix_inputtables_id'), table_name='inputtables')
    op.drop_table('inputtables')
    # ### end Alembic commands ###
