"""feat: input table and output table

Revision ID: 76e5000db086
Revises: 
Create Date: 2022-09-20 12:55:11.779854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76e5000db086'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inputs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sepal_length', sa.Float(), nullable=False),
    sa.Column('sepal_width', sa.Float(), nullable=False),
    sa.Column('petal_length', sa.Float(), nullable=False),
    sa.Column('petal_width', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inputs_id'), 'inputs', ['id'], unique=False)
    op.create_table('outputs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('executed_at', sa.Float(), nullable=False),
    sa.Column('pred_class', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outputs_id'), 'outputs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outputs_id'), table_name='outputs')
    op.drop_table('outputs')
    op.drop_index(op.f('ix_inputs_id'), table_name='inputs')
    op.drop_table('inputs')
    # ### end Alembic commands ###
